version: "3"

services:
  monolithic:
    build: ./monolithic

  users:
    build: ./microservices/user-service

  cars:
    build: ./microservices/car-service

  books:
    build: ./microservices/book-service

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - monolithic
      - users
      - books
      - cars
